[package]
name = "q2_12"
version = "0.1.0"
authors = ["cipepser <respepic@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../../chap1_Intrudction/common" }
basic = { path = "../basic"}
rug = "1.10.0"