[package]
name = "chap5-basic"
version = "0.1.0"
authors = ["cipepser <respepic@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../../chap1_Intrudction/common" }
rand = "0.7.3"
array_based_lists = { package = "basic", path = "../../chap2_Array-Based_Lists/basic" }